apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: ingress-nginx
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: shwetha12712712/frontend:1
          ports:
            - containerPort: 3000  

---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: ingress-nginx
  labels:
    app: react-app
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP